#!/bin/sh

make mostlyclean
make clean
make maintainer-clean

find . | grep -E ".Makefile\.in" | xargs rm
find . | grep -E "\.deps$" | xargs rm -rf

rm COPYING INSTALL install-sh missing compile depcomp aclocal.m4 configure
rm config.sub config.guess ltmain.sh test-driver autom4te.cache
