#!/usr/bin/python3

try:
    while True:
        line = input()
        line = line.replace('success', '\033[32msuccess\033[0m')
        line = line.replace('OK', '\033[32mOK\033[0m')
        line = line.replace('failure', '\033[31mfailure\033[0m')
        line = line.replace('FAILED', '\033[31mFAILED\033[0m')
        print(line)
except EOFError:
    pass
